import { createPublicClient, createWalletClient, custom, formatEther, http, isAddress, keccak256, parseEther, toBytes } from "viem";
import type { Address, EIP1193Provider, Hash } from "viem";
declare global { interface Window { ethereum?: EIP1193Provider; } }
type Artifact = { abi: readonly unknown[]; bytecode: Hash };
const arc = { id: 5042002, name: "Arc Testnet", nativeCurrency: { name: "USDC", symbol: "USDC", decimals: 18 }, rpcUrls: { default: { http: ["https://rpc.testnet.arc.network"] } }, blockExplorers: { default: { name: "ArcScan", url: "https://testnet.arcscan.app" } } } as const;
const publicClient = createPublicClient({ chain: arc, transport: http() }); const chainId = "0x4cef52"; const storageKey = "ArcStreamingPayroll.v2.contractAddress";
let provider: EIP1193Provider | null = null; let wallet: ReturnType<typeof createWalletClient> | null = null; let account: Address | null = null; let artifact: Artifact | null = null; let contract = (localStorage.getItem(storageKey) ?? "") as Address | "";
const el = {
  connect: document.querySelector<HTMLButtonElement>("#connect")!, wallet: document.querySelector<HTMLElement>("#wallet")!, balance: document.querySelector<HTMLElement>("#balance")!, contract: document.querySelector<HTMLInputElement>("#contract")!, save: document.querySelector<HTMLButtonElement>("#save")!, deploy: document.querySelector<HTMLButtonElement>("#deploy")!,
  streamId: document.querySelector<HTMLInputElement>("#streamId")!, recipient: document.querySelector<HTMLInputElement>("#recipient")!, amount: document.querySelector<HTMLInputElement>("#amount")!, start: document.querySelector<HTMLInputElement>("#start")!, end: document.querySelector<HTMLInputElement>("#end")!, metadata: document.querySelector<HTMLInputElement>("#metadata")!, create: document.querySelector<HTMLButtonElement>("#create")!, load: document.querySelector<HTMLButtonElement>("#load")!, withdraw: document.querySelector<HTMLButtonElement>("#withdraw")!, cancel: document.querySelector<HTMLButtonElement>("#cancel")!, status: document.querySelector<HTMLElement>("#status")!, result: document.querySelector<HTMLElement>("#result")!,
};
function localDateTimeValue(date: Date): string { const pad = (value: number) => String(value).padStart(2, "0"); return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`; }
el.contract.value = contract; const now = Date.now(); const minute = 60_000; const roundedNow = Math.ceil(now / minute) * minute; const today = new Date(now).toISOString().slice(0, 10); el.streamId.value = `arc-stream-${today}`; el.amount.value = "0.02"; el.start.value = localDateTimeValue(new Date(roundedNow + 2 * minute)); el.end.value = localDateTimeValue(new Date(roundedNow + 10 * minute)); el.metadata.value = `local:arc-stream:${today}`;
function setStatus(message: string, hash?: Hash): void { el.status.innerHTML = hash ? `${message} <a href="https://testnet.arcscan.app/tx/${hash}" target="_blank" rel="noreferrer">ArcScan</a>` : message; }
function requireContract(): Address { if (!isAddress(contract)) throw new Error("Set a valid ArcStreamingPayroll contract address first."); return contract; }
async function getArtifact(): Promise<Artifact> { artifact ??= await fetch("./artifacts/ArcStreamingPayroll.json").then((response) => response.json()) as Artifact; return artifact; }
async function connect(): Promise<void> { provider = window.ethereum ?? null; if (!provider) throw new Error("MetaMask was not found."); await provider.request({ method: "wallet_switchEthereumChain", params: [{ chainId }] }); const accounts = await provider.request({ method: "eth_requestAccounts" }) as string[]; account = accounts[0] as Address; wallet = createWalletClient({ account, chain: arc, transport: custom(provider) }); el.wallet.textContent = account; el.recipient.value = account; el.balance.textContent = `${formatEther(await publicClient.getBalance({ address: account }))} USDC`; setStatus("Wallet connected. Self-stream is enabled for testing."); }
async function ensureWallet(): Promise<void> { if (!wallet || !account) await connect(); if (!wallet || !account) throw new Error("Wallet connection failed."); }
function streamHash(): Hash { const value = el.streamId.value.trim(); if (!value) throw new Error("Stream ID is required."); return keccak256(toBytes(value)); }
function schedule(): [bigint, bigint] { const startMs = new Date(el.start.value).getTime(); const endMs = new Date(el.end.value).getTime(); if (!Number.isFinite(startMs) || !Number.isFinite(endMs)) throw new Error("Enter both start and end times."); const start = BigInt(Math.floor(startMs / 1000)); const end = BigInt(Math.floor(endMs / 1000)); const now = BigInt(Math.floor(Date.now() / 1000)); if (start <= now + 30n || end <= start) throw new Error("Start must be at least 30 seconds from now, and end must be later."); return [start, end]; }
async function deploy(): Promise<void> { await ensureWallet(); const compiled = await getArtifact(); setStatus("Waiting for MetaMask: deploy ArcStreamingPayroll..."); const hash = await wallet!.deployContract({ abi: compiled.abi as any, bytecode: compiled.bytecode } as any); const receipt = await publicClient.waitForTransactionReceipt({ hash }); if (!receipt.contractAddress) throw new Error("Deployment receipt did not include a contract address."); contract = receipt.contractAddress; el.contract.value = contract; localStorage.setItem(storageKey, contract); setStatus("ArcStreamingPayroll deployed.", hash); }
async function createStream(): Promise<void> { await ensureWallet(); const compiled = await getArtifact(); if (!isAddress(el.recipient.value.trim())) throw new Error("Recipient must be a valid address."); const [start, end] = schedule(); setStatus("Waiting for MetaMask: fund streaming payroll..."); const hash = await wallet!.writeContract({ address: requireContract(), abi: compiled.abi as any, functionName: "createStream", args: [streamHash(), el.recipient.value.trim() as Address, start, end, el.metadata.value.trim()], value: parseEther(el.amount.value) } as any); await publicClient.waitForTransactionReceipt({ hash }); setStatus("Streaming payroll created.", hash); await loadStream(); }
async function loadStream(): Promise<void> { const compiled = await getArtifact(); const stream = await publicClient.readContract({ address: requireContract(), abi: compiled.abi as any, functionName: "getStream", args: [streamHash()] } as any) as any; const vested = await publicClient.readContract({ address: requireContract(), abi: compiled.abi as any, functionName: "vestedAmount", args: [streamHash()] } as any) as bigint; const status = ["unknown", "active", "completed", "cancelled"]; el.result.textContent = JSON.stringify({ streamId: streamHash(), sender: stream.sender ?? stream[0], recipient: stream.recipient ?? stream[1], totalAmount: `${formatEther(stream.totalAmount ?? stream[2])} USDC`, withdrawn: `${formatEther(stream.withdrawn ?? stream[3])} USDC`, currentlyVested: `${formatEther(vested)} USDC`, startTime: new Date(Number(stream.startTime ?? stream[4]) * 1000).toISOString(), endTime: new Date(Number(stream.endTime ?? stream[5]) * 1000).toISOString(), status: status[Number(stream.status ?? stream[7])] ?? "unknown", metadataURI: stream.metadataURI ?? stream[6] }, null, 2); const state = Number(stream.status ?? stream[7]); el.withdraw.disabled = state !== 1; el.cancel.disabled = state !== 1; setStatus("Stream loaded."); }
async function withdraw(): Promise<void> { await ensureWallet(); const compiled = await getArtifact(); const hash = await wallet!.writeContract({ address: requireContract(), abi: compiled.abi as any, functionName: "withdraw", args: [streamHash()] } as any); await publicClient.waitForTransactionReceipt({ hash }); setStatus("Vested amount withdrawn.", hash); await loadStream(); }
async function cancel(): Promise<void> { await ensureWallet(); const compiled = await getArtifact(); const hash = await wallet!.writeContract({ address: requireContract(), abi: compiled.abi as any, functionName: "cancel", args: [streamHash()] } as any); await publicClient.waitForTransactionReceipt({ hash }); setStatus("Stream cancelled and balances settled.", hash); await loadStream(); }
el.connect.addEventListener("click", () => void connect().catch((error) => setStatus(error instanceof Error ? error.message : "Connection failed."))); el.save.addEventListener("click", () => { contract = el.contract.value.trim() as Address; localStorage.setItem(storageKey, contract); setStatus("Contract address saved."); }); el.deploy.addEventListener("click", () => void deploy().catch((error) => setStatus(error instanceof Error ? error.message : "Deployment failed."))); el.create.addEventListener("click", () => void createStream().catch((error) => setStatus(error instanceof Error ? error.message : "Create failed."))); el.load.addEventListener("click", () => void loadStream().catch((error) => setStatus(error instanceof Error ? error.message : "Load failed."))); el.withdraw.addEventListener("click", () => void withdraw().catch((error) => setStatus(error instanceof Error ? error.message : "Withdraw failed."))); el.cancel.addEventListener("click", () => void cancel().catch((error) => setStatus(error instanceof Error ? error.message : "Cancel failed."))); el.withdraw.disabled = true; el.cancel.disabled = true;
