import { createPublicClient, createWalletClient, custom, formatEther, http, isAddress, keccak256, parseEther, toBytes } from "viem";
import type { Address, EIP1193Provider, Hash } from "viem";
declare global { interface Window { ethereum?: EIP1193Provider; } }
type Artifact = { abi: readonly unknown[]; bytecode: Hash };
const arc = { id: 5042002, name: "Arc Testnet", nativeCurrency: { name: "USDC", symbol: "USDC", decimals: 18 }, rpcUrls: { default: { http: ["https://rpc.testnet.arc.network"] } }, blockExplorers: { default: { name: "ArcScan", url: "https://testnet.arcscan.app" } } } as const;
const publicClient = createPublicClient({ chain: arc, transport: http() });
const chainId = "0x4cef52"; const storageKey = "ArcUsageBilling.contractAddress";
let provider: EIP1193Provider | null = null; let wallet: ReturnType<typeof createWalletClient> | null = null; let account: Address | null = null; let artifact: Artifact | null = null;
let contract = (localStorage.getItem(storageKey) ?? "") as Address | "";
const el = {
  connect: document.querySelector<HTMLButtonElement>("#connect")!, wallet: document.querySelector<HTMLElement>("#wallet")!, balance: document.querySelector<HTMLElement>("#balance")!,
  contract: document.querySelector<HTMLInputElement>("#contract")!, save: document.querySelector<HTMLButtonElement>("#save")!, deploy: document.querySelector<HTMLButtonElement>("#deploy")!,
  chargeId: document.querySelector<HTMLInputElement>("#chargeId")!, payer: document.querySelector<HTMLInputElement>("#payer")!, units: document.querySelector<HTMLInputElement>("#units")!, unitPrice: document.querySelector<HTMLInputElement>("#unitPrice")!, expiry: document.querySelector<HTMLInputElement>("#expiry")!, metadata: document.querySelector<HTMLInputElement>("#metadata")!,
  create: document.querySelector<HTMLButtonElement>("#create")!, load: document.querySelector<HTMLButtonElement>("#load")!, pay: document.querySelector<HTMLButtonElement>("#pay")!, cancel: document.querySelector<HTMLButtonElement>("#cancel")!, status: document.querySelector<HTMLElement>("#status")!, result: document.querySelector<HTMLElement>("#result")!,
};
el.contract.value = contract; const date = new Date().toISOString().slice(0, 10); el.chargeId.value = `arc-usage-${date}`; el.units.value = "10"; el.unitPrice.value = "0.001"; el.expiry.value = new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString().slice(0, 16); el.metadata.value = `local:arc-usage:${date}`;
function setStatus(message: string, hash?: Hash): void { el.status.innerHTML = hash ? `${message} <a href="https://testnet.arcscan.app/tx/${hash}" target="_blank" rel="noreferrer">ArcScan</a>` : message; }
function requireContract(): Address { if (!isAddress(contract)) throw new Error("Set a valid ArcUsageBilling contract address first."); return contract; }
async function getArtifact(): Promise<Artifact> { artifact ??= await fetch("./artifacts/ArcUsageBilling.json").then((response) => response.json()) as Artifact; return artifact; }
async function connect(): Promise<void> { provider = window.ethereum ?? null; if (!provider) throw new Error("MetaMask was not found."); await provider.request({ method: "wallet_switchEthereumChain", params: [{ chainId }] }); const accounts = await provider.request({ method: "eth_requestAccounts" }) as string[]; account = accounts[0] as Address; wallet = createWalletClient({ account, chain: arc, transport: custom(provider) }); el.wallet.textContent = account; el.payer.value = account; el.balance.textContent = `${formatEther(await publicClient.getBalance({ address: account }))} USDC`; setStatus("Wallet connected."); }
async function ensureWallet(): Promise<void> { if (!wallet || !account) await connect(); if (!wallet || !account) throw new Error("Wallet connection failed."); }
function chargeHash(): Hash { const value = el.chargeId.value.trim(); if (!value) throw new Error("Charge ID is required."); return keccak256(toBytes(value)); }
function expirySeconds(): bigint { const value = BigInt(Math.floor(new Date(el.expiry.value).getTime() / 1000)); if (value <= BigInt(Math.floor(Date.now() / 1000))) throw new Error("Expiry must be in the future."); return value; }
async function deploy(): Promise<void> { await ensureWallet(); const compiled = await getArtifact(); setStatus("Waiting for MetaMask: deploy ArcUsageBilling..."); const hash = await wallet!.deployContract({ abi: compiled.abi as any, bytecode: compiled.bytecode } as any); const receipt = await publicClient.waitForTransactionReceipt({ hash }); if (!receipt.contractAddress) throw new Error("Deployment receipt did not include a contract address."); contract = receipt.contractAddress; el.contract.value = contract; localStorage.setItem(storageKey, contract); setStatus("ArcUsageBilling deployed.", hash); }
async function createCharge(): Promise<void> { await ensureWallet(); const compiled = await getArtifact(); if (!isAddress(el.payer.value.trim())) throw new Error("Payer address must be valid."); const units = BigInt(el.units.value); const unitPrice = parseEther(el.unitPrice.value); setStatus("Waiting for MetaMask: create usage charge..."); const hash = await wallet!.writeContract({ address: requireContract(), abi: compiled.abi as any, functionName: "createCharge", args: [chargeHash(), el.payer.value.trim() as Address, units, unitPrice, expirySeconds(), el.metadata.value.trim()] } as any); await publicClient.waitForTransactionReceipt({ hash }); setStatus("Usage charge created.", hash); await loadCharge(); }
async function loadCharge(): Promise<void> { const compiled = await getArtifact(); const charge = await publicClient.readContract({ address: requireContract(), abi: compiled.abi as any, functionName: "getCharge", args: [chargeHash()] } as any) as any; const status = ["unknown", "open", "paid", "cancelled"]; el.result.textContent = JSON.stringify({ chargeId: chargeHash(), merchant: charge.merchant ?? charge[0], payer: charge.payer ?? charge[1], units: String(charge.units ?? charge[2]), unitPrice: `${formatEther(charge.unitPrice ?? charge[3])} USDC`, totalAmount: `${formatEther(charge.totalAmount ?? charge[4])} USDC`, expiresAt: new Date(Number(charge.expiresAt ?? charge[6]) * 1000).toISOString(), status: status[Number(charge.status ?? charge[9])] ?? "unknown", metadataURI: charge.metadataURI ?? charge[8] }, null, 2); const state = Number(charge.status ?? charge[9]); el.pay.disabled = state !== 1; el.cancel.disabled = state !== 1; setStatus("Usage charge loaded."); }
async function payCharge(): Promise<void> { await ensureWallet(); const compiled = await getArtifact(); const units = BigInt(el.units.value); const total = units * parseEther(el.unitPrice.value); setStatus("Waiting for MetaMask: pay usage charge..."); const hash = await wallet!.writeContract({ address: requireContract(), abi: compiled.abi as any, functionName: "payCharge", args: [chargeHash()], value: total } as any); await publicClient.waitForTransactionReceipt({ hash }); setStatus("Usage charge paid and settled to merchant.", hash); await loadCharge(); }
async function cancelCharge(): Promise<void> { await ensureWallet(); const compiled = await getArtifact(); const hash = await wallet!.writeContract({ address: requireContract(), abi: compiled.abi as any, functionName: "cancelCharge", args: [chargeHash()] } as any); await publicClient.waitForTransactionReceipt({ hash }); setStatus("Usage charge cancelled.", hash); await loadCharge(); }
el.connect.addEventListener("click", () => void connect().catch((error) => setStatus(error instanceof Error ? error.message : "Connection failed."))); el.save.addEventListener("click", () => { contract = el.contract.value.trim() as Address; localStorage.setItem(storageKey, contract); setStatus("Contract address saved."); }); el.deploy.addEventListener("click", () => void deploy().catch((error) => setStatus(error instanceof Error ? error.message : "Deployment failed."))); el.create.addEventListener("click", () => void createCharge().catch((error) => setStatus(error instanceof Error ? error.message : "Create failed."))); el.load.addEventListener("click", () => void loadCharge().catch((error) => setStatus(error instanceof Error ? error.message : "Load failed."))); el.pay.addEventListener("click", () => void payCharge().catch((error) => setStatus(error instanceof Error ? error.message : "Payment failed."))); el.cancel.addEventListener("click", () => void cancelCharge().catch((error) => setStatus(error instanceof Error ? error.message : "Cancel failed."))); el.pay.disabled = true; el.cancel.disabled = true;
