import { createPublicClient, createWalletClient, custom, formatEther, http, isAddress, keccak256, parseEther, toBytes } from "viem";
import type { Address, EIP1193Provider, Hash } from "viem";
declare global { interface Window { ethereum?: EIP1193Provider; } }
type Artifact = { abi: readonly unknown[]; bytecode: Hash };
const arc = { id: 5042002, name: "Arc Testnet", nativeCurrency: { name: "USDC", symbol: "USDC", decimals: 18 }, rpcUrls: { default: { http: ["https://rpc.testnet.arc.network"] } }, blockExplorers: { default: { name: "ArcScan", url: "https://testnet.arcscan.app" } } } as const;
const publicClient = createPublicClient({ chain: arc, transport: http() }); const chainId = "0x4cef52"; const storageKey = "ArcRefundablePayment.contractAddress";
let provider: EIP1193Provider | null = null; let wallet: ReturnType<typeof createWalletClient> | null = null; let account: Address | null = null; let artifact: Artifact | null = null; let contract = (localStorage.getItem(storageKey) ?? "") as Address | "";
const el = { connect: document.querySelector<HTMLButtonElement>("#connect")!, wallet: document.querySelector<HTMLElement>("#wallet")!, balance: document.querySelector<HTMLElement>("#balance")!, contract: document.querySelector<HTMLInputElement>("#contract")!, save: document.querySelector<HTMLButtonElement>("#save")!, deploy: document.querySelector<HTMLButtonElement>("#deploy")!, paymentId: document.querySelector<HTMLInputElement>("#paymentId")!, payer: document.querySelector<HTMLInputElement>("#payer")!, amount: document.querySelector<HTMLInputElement>("#amount")!, expiry: document.querySelector<HTMLInputElement>("#expiry")!, metadata: document.querySelector<HTMLInputElement>("#metadata")!, reason: document.querySelector<HTMLInputElement>("#reason")!, create: document.querySelector<HTMLButtonElement>("#create")!, load: document.querySelector<HTMLButtonElement>("#load")!, pay: document.querySelector<HTMLButtonElement>("#pay")!, request: document.querySelector<HTMLButtonElement>("#request")!, refund: document.querySelector<HTMLButtonElement>("#refund")!, settle: document.querySelector<HTMLButtonElement>("#settle")!, cancel: document.querySelector<HTMLButtonElement>("#cancel")!, status: document.querySelector<HTMLElement>("#status")!, result: document.querySelector<HTMLElement>("#result")! };
function localDateTimeValue(date: Date): string { const pad = (value: number) => String(value).padStart(2, "0"); return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`; }
el.contract.value = contract; const now = Date.now(); const today = new Date(now).toISOString().slice(0, 10); const roundedNow = Math.ceil(now / 60_000) * 60_000; el.paymentId.value = `arc-refund-${today}`; el.amount.value = "0.01"; el.expiry.value = localDateTimeValue(new Date(roundedNow + 10 * 60_000)); el.metadata.value = `local:arc-refundable-payment:${today}`; el.reason.value = `local:arc-refund:${today}:reason`;
function setStatus(message: string, hash?: Hash): void { el.status.innerHTML = hash ? `${message} <a href="https://testnet.arcscan.app/tx/${hash}" target="_blank" rel="noreferrer">ArcScan</a>` : message; }
function requireContract(): Address { if (!isAddress(contract)) throw new Error("Set a valid ArcRefundablePayment contract address first."); return contract; }
async function getArtifact(): Promise<Artifact> { artifact ??= await fetch("./artifacts/ArcRefundablePayment.json").then((response) => response.json()) as Artifact; return artifact; }
async function connect(): Promise<void> { provider = window.ethereum ?? null; if (!provider) throw new Error("MetaMask was not found."); await provider.request({ method: "wallet_switchEthereumChain", params: [{ chainId }] }); const accounts = await provider.request({ method: "eth_requestAccounts" }) as string[]; account = accounts[0] as Address; wallet = createWalletClient({ account, chain: arc, transport: custom(provider) }); el.wallet.textContent = account; el.payer.value = account; el.balance.textContent = `${formatEther(await publicClient.getBalance({ address: account }))} USDC`; setStatus("Wallet connected."); }
async function ensureWallet(): Promise<void> { if (!wallet || !account) await connect(); if (!wallet || !account) throw new Error("Wallet connection failed."); }
function paymentHash(): Hash { const value = el.paymentId.value.trim(); if (!value) throw new Error("Payment ID is required."); return keccak256(toBytes(value)); }
function expirySeconds(): bigint { const value = BigInt(Math.floor(new Date(el.expiry.value).getTime() / 1000)); if (value <= BigInt(Math.floor(Date.now() / 1000)) + 30n) throw new Error("Expiry must be in the future."); return value; }
async function deploy(): Promise<void> { await ensureWallet(); const compiled = await getArtifact(); setStatus("Waiting for MetaMask: deploy ArcRefundablePayment..."); const hash = await wallet!.deployContract({ abi: compiled.abi as any, bytecode: compiled.bytecode } as any); const receipt = await publicClient.waitForTransactionReceipt({ hash }); if (!receipt.contractAddress) throw new Error("Deployment receipt did not include a contract address."); contract = receipt.contractAddress; el.contract.value = contract; localStorage.setItem(storageKey, contract); setStatus("ArcRefundablePayment deployed.", hash); }
async function createPayment(): Promise<void> { await ensureWallet(); const compiled = await getArtifact(); if (!isAddress(el.payer.value.trim())) throw new Error("Payer address must be valid."); setStatus("Waiting for MetaMask: create refundable payment..."); const hash = await wallet!.writeContract({ address: requireContract(), abi: compiled.abi as any, functionName: "createPayment", args: [paymentHash(), el.payer.value.trim() as Address, parseEther(el.amount.value), expirySeconds(), el.metadata.value.trim()] } as any); await publicClient.waitForTransactionReceipt({ hash }); setStatus("Refundable payment created.", hash); await loadPayment(); }
async function readPayment(expectedState?: number): Promise<any> { const compiled = await getArtifact(); let payment: any; for (let attempt = 0; attempt < 8; attempt++) { payment = await publicClient.readContract({ address: requireContract(), abi: compiled.abi as any, functionName: "getPayment", args: [paymentHash()] } as any); const state = Number(payment.status ?? payment[6]); if ((expectedState === undefined && state !== 0) || state === expectedState || attempt === 7) return payment; await new Promise((resolve) => setTimeout(resolve, 1200)); } return payment; }
async function loadPayment(expectedState?: number): Promise<void> { const payment = await readPayment(expectedState); const statuses = ["unknown", "open", "paid", "refund requested", "refunded", "settled", "cancelled"]; const state = Number(payment.status ?? payment[6]); el.result.textContent = JSON.stringify({ paymentId: paymentHash(), merchant: payment.merchant ?? payment[0], payer: payment.payer ?? payment[1], amount: `${formatEther(payment.amount ?? payment[2])} USDC`, expiresAt: new Date(Number(payment.expiresAt ?? payment[4]) * 1000).toISOString(), status: statuses[state] ?? "unknown", metadataURI: payment.metadataURI ?? payment[5] }, null, 2); el.pay.disabled = state !== 1; el.request.disabled = state !== 2; el.refund.disabled = state !== 3; el.settle.disabled = state !== 2; el.cancel.disabled = state !== 1; setStatus(state === 0 ? "No payment exists for this ID. Create payment first." : "Payment loaded."); }
async function call(name: string, args: unknown[] = [], value?: bigint): Promise<void> { await ensureWallet(); const compiled = await getArtifact(); const hash = await wallet!.writeContract({ address: requireContract(), abi: compiled.abi as any, functionName: name, args: [paymentHash(), ...args], ...(value === undefined ? {} : { value }) } as any); await publicClient.waitForTransactionReceipt({ hash }); const expectedState = ({ pay: 2, requestRefund: 3, refund: 4, settle: 5, cancel: 6 } as Record<string, number>)[name]; setStatus(`${name} confirmed. Refreshing payment state...`, hash); await loadPayment(expectedState); }
el.connect.addEventListener("click", () => void connect().catch((error) => setStatus(error instanceof Error ? error.message : "Connection failed."))); el.save.addEventListener("click", () => { contract = el.contract.value.trim() as Address; localStorage.setItem(storageKey, contract); setStatus("Contract address saved."); }); el.deploy.addEventListener("click", () => void deploy().catch((error) => setStatus(error instanceof Error ? error.message : "Deployment failed."))); el.create.addEventListener("click", () => void createPayment().catch((error) => setStatus(error instanceof Error ? error.message : "Create failed."))); el.load.addEventListener("click", () => void loadPayment().catch((error) => setStatus(error instanceof Error ? error.message : "Load failed."))); el.pay.addEventListener("click", () => void call("pay", [], parseEther(el.amount.value)).catch((error) => setStatus(error instanceof Error ? error.message : "Pay failed."))); el.request.addEventListener("click", () => void call("requestRefund", [el.reason.value.trim()]).catch((error) => setStatus(error instanceof Error ? error.message : "Request failed."))); el.refund.addEventListener("click", () => void call("refund").catch((error) => setStatus(error instanceof Error ? error.message : "Refund failed."))); el.settle.addEventListener("click", () => void call("settle").catch((error) => setStatus(error instanceof Error ? error.message : "Settle failed."))); el.cancel.addEventListener("click", () => void call("cancel").catch((error) => setStatus(error instanceof Error ? error.message : "Cancel failed."))); for (const button of [el.pay, el.request, el.refund, el.settle, el.cancel]) button.disabled = true;
