import { AppKit } from "@circle-fin/app-kit";
import type { BridgeParams, BridgeResult, EstimateResult } from "@circle-fin/app-kit";
import { createViemAdapterFromProvider } from "@circle-fin/adapter-viem-v2";
import { createPublicClient, formatUnits, http } from "viem";
import type { EIP1193Provider } from "viem";

declare global { interface Window { ethereum?: EIP1193Provider; } }
type Chain = "Arc_Testnet" | "Ethereum_Sepolia" | "Base_Sepolia";
const chainMeta = {
  Arc_Testnet: { id: 5042002, name: "Arc Testnet", rpcUrl: "https://rpc.testnet.arc.network", explorerUrl: "https://testnet.arcscan.app", usdcAddress: "0x3600000000000000000000000000000000000000" },
  Ethereum_Sepolia: { id: 11155111, name: "Ethereum Sepolia", rpcUrl: "https://ethereum-sepolia-rpc.publicnode.com", explorerUrl: "https://sepolia.etherscan.io", usdcAddress: "0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238" },
  Base_Sepolia: { id: 84532, name: "Base Sepolia", rpcUrl: "https://sepolia.base.org", explorerUrl: "https://sepolia.basescan.org", usdcAddress: "0x036CbD53842c5426634e7929541eC2318f3dCF7e" },
} as const;
const abi = [{ type: "function", name: "balanceOf", stateMutability: "view", inputs: [{ name: "account", type: "address" }], outputs: [{ type: "uint256" }] }] as const;
const kit = new AppKit(); let adapter: Awaited<ReturnType<typeof createViemAdapterFromProvider>> | null = null; let address = "";
function routeBridgeApisThroughLocalProxy(): void {
  const originalFetch = globalThis.fetch.bind(globalThis);
  globalThis.fetch = (input: RequestInfo | URL, init?: RequestInit) => {
    const rawUrl = typeof input === "string" ? input : input instanceof URL ? input.toString() : input.url;
    if (rawUrl.startsWith("https://iris-api-sandbox.circle.com/")) return originalFetch(rawUrl.replace("https://iris-api-sandbox.circle.com", "/circle-iris-sandbox"), init);
    if (rawUrl.startsWith("https://iris-api.circle.com/")) return originalFetch(rawUrl.replace("https://iris-api.circle.com", "/circle-iris"), init);
    return originalFetch(input, init);
  };
}
routeBridgeApisThroughLocalProxy();
const el = { connect: document.querySelector<HTMLButtonElement>("#connect")!, direction: document.querySelector<HTMLSelectElement>("#direction")!, source: document.querySelector<HTMLElement>("#source")!, destination: document.querySelector<HTMLElement>("#destination")!, recipient: document.querySelector<HTMLInputElement>("#recipient")!, amount: document.querySelector<HTMLInputElement>("#amount")!, speed: document.querySelector<HTMLSelectElement>("#speed")!, estimate: document.querySelector<HTMLButtonElement>("#estimate")!, route: document.querySelector<HTMLButtonElement>("#route")!, sourceBalance: document.querySelector<HTMLElement>("#sourceBalance")!, destinationBalance: document.querySelector<HTMLElement>("#destinationBalance")!, status: document.querySelector<HTMLElement>("#status")!, estimateBox: document.querySelector<HTMLElement>("#estimateBox")!, resultBox: document.querySelector<HTMLElement>("#resultBox")! };
function currentChains(): { source: Chain; destination: Chain } { return el.direction.value === "to-arc" ? { source: el.source.dataset.chain as Chain, destination: "Arc_Testnet" } : { source: "Arc_Testnet", destination: el.destination.dataset.chain as Chain }; }
function setStatus(message: string): void { el.status.textContent = message; }
function stringify(value: unknown): string { return JSON.stringify(value, (_key, value) => typeof value === "bigint" ? value.toString() : value, 2); }
function errorMessage(error: unknown): string { console.error(error); return error instanceof Error ? error.message : "Unknown error."; }
function updateRouteLabels(): void { const toArc = el.direction.value === "to-arc"; el.source.textContent = toArc ? "Select source chain" : "Arc Testnet"; el.destination.textContent = toArc ? "Arc Testnet" : "Select destination chain"; (toArc ? el.source : el.destination).innerHTML = `<select id="routeChain"><option value="Ethereum_Sepolia">Ethereum Sepolia</option><option value="Base_Sepolia">Base Sepolia</option></select>`; const select = document.querySelector<HTMLSelectElement>("#routeChain")!; (toArc ? el.source : el.destination).dataset.chain = select.value; select.addEventListener("change", () => { (toArc ? el.source : el.destination).dataset.chain = select.value; void refreshBalances(); }); void refreshBalances(); }
function bridgeParams(): BridgeParams { if (!adapter) throw new Error("Connect MetaMask first."); const { source, destination } = currentChains(); const recipient = el.recipient.value.trim() || address; if (!recipient) throw new Error("Recipient address is required."); return { from: { adapter, chain: source }, to: { adapter, chain: destination, recipientAddress: recipient }, amount: el.amount.value.trim(), token: "USDC", config: { transferSpeed: el.speed.value as "FAST" | "SLOW", batchTransactions: false } }; }
function createClient(chain: Chain) { const meta = chainMeta[chain]; return createPublicClient({ chain: { id: meta.id, name: meta.name, nativeCurrency: { name: "USDC", symbol: "USDC", decimals: 18 }, rpcUrls: { default: { http: [meta.rpcUrl] } } }, transport: http(meta.rpcUrl) }); }
async function balance(chain: Chain, owner: string): Promise<string> { const value = await createClient(chain).readContract({ address: chainMeta[chain].usdcAddress as `0x${string}`, abi, functionName: "balanceOf", args: [owner as `0x${string}`] }); return formatUnits(value, 6); }
async function refreshBalances(): Promise<void> { if (!address) return; const { source, destination } = currentChains(); try { const [sourceValue, destinationValue] = await Promise.all([balance(source, address), balance(destination, el.recipient.value.trim() || address)]); el.sourceBalance.textContent = `${sourceValue} USDC`; el.destinationBalance.textContent = `${destinationValue} USDC`; } catch (error) { setStatus(`Balance read failed: ${errorMessage(error)}`); } }
async function connect(): Promise<void> { if (!window.ethereum) throw new Error("MetaMask provider not found."); setStatus("Connecting MetaMask..."); const accounts = await window.ethereum.request({ method: "eth_requestAccounts" }) as string[]; address = accounts[0] ?? ""; adapter = await createViemAdapterFromProvider({ provider: window.ethereum }); el.recipient.value = address; el.estimate.disabled = false; el.route.disabled = false; updateRouteLabels(); setStatus("Ready. Review the route before signing."); }
function renderEstimate(estimate: EstimateResult): void { el.estimateBox.innerHTML = `<div><strong>Amount</strong><span>${estimate.amount} ${estimate.token}</span></div><div><strong>Route</strong><span>${estimate.source.chain} → ${estimate.destination.chain}</span></div><div><strong>Fees</strong><span>${estimate.fees.map((fee) => `${fee.type}: ${fee.amount ?? "n/a"} ${fee.token}`).join(", ") || "-"}</span></div>`; }
function renderResult(result: BridgeResult): void { el.resultBox.innerHTML = `<div><strong>State</strong><span>${result.state}</span></div><div><strong>Source</strong><span>${result.source.chain.chain}</span></div><div><strong>Destination</strong><span>${result.destination.chain.chain}</span></div>${result.steps.map((step) => `<div><strong>${step.name}</strong><span>${step.state} · ${step.txHash ?? "pending"}</span>${step.txHash ? `<a href="${chainMeta[currentChains().source].explorerUrl}/tx/${step.txHash}" target="_blank" rel="noreferrer">ArcScan / explorer</a>` : ""}</div>`).join("")}`; localStorage.setItem("ArcCrosschainRouter.lastRoute", JSON.stringify(result, (_key, value) => typeof value === "bigint" ? value.toString() : value)); }
async function estimate(): Promise<void> { if (!adapter) await connect(); setStatus("Estimating cross-chain route..."); try { renderEstimate(await kit.estimateBridge(bridgeParams())); setStatus("Estimate ready. No transaction has been submitted."); } catch (error) { el.estimateBox.textContent = stringify(error); setStatus(`Estimate failed: ${errorMessage(error)}`); } }
async function route(): Promise<void> { if (!adapter) await connect(); el.route.disabled = true; try { setStatus("Waiting for MetaMask approval and burn/mint signatures..."); const params = bridgeParams(); await kit.estimateBridge(params); const result = await kit.bridge(params); renderResult(result); await refreshBalances(); setStatus("Cross-chain route completed or is being finalized."); } catch (error) { el.resultBox.textContent = stringify(error); setStatus(`Route failed: ${errorMessage(error)}`); } finally { el.route.disabled = false; } }
el.connect.addEventListener("click", () => void connect().catch((error) => setStatus(errorMessage(error)))); el.direction.addEventListener("change", updateRouteLabels); el.estimate.addEventListener("click", () => void estimate()); el.route.addEventListener("click", () => void route()); el.recipient.addEventListener("change", () => void refreshBalances()); updateRouteLabels();
